#!/usr/bin/env bash
# prints a string 10 times using while loop and on the ninth iteration it prints hi

i=1

while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
